default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: crm_system_backend_development

test:
  <<: *default
  database: crm_system_backend_test

production:
  <<: *default
  database: crm_system_backend_production
  username: crm_system_backend
  password: <%= ENV['CRM_SYSTEM_BACKEND_DATABASE_PASSWORD'] %>
